# =====================================================
# Trabajo Práctico 2C 2025 - Red Neuronal Lineal
# =====================================================
# Alumnos: Bravo...
# Materia: Álgebra Lineal Computacional - FCEN UBA
# =====================================================

## 1. Lectura de datos

Implementar la función `cargarDataset(carpeta)` que lea las matrices de embeddings 
precalculadas (en formato .npy) de las carpetas `train` y `val`, y genere:

- $X_t$, $Y_t$ → entrenamiento
- $X_v$, $Y_v$ → validación

Cada columna de $X$ corresponde a un embedding.
Cada columna de $Y$ es un vector $[1,0]^T$ (gato) o $[0,1]^T$ (perro).


In [1]:
import numpy as np
from moduloALC import *

# Cargamos los datos para ver e interpretar su forma
carpetaDatos = r'template-alumnos\cats_and_dogs'
Xt, Yt, Xv, Yv = cargarDataset(carpetaDatos)
print("X_training:", Xt.shape, "Y_training:", Yt.shape)
print("Xv:", Xv.shape, "Yv:", Yv.shape)
print("Etiquetas únicas:", np.unique(Yt), np.unique(Yv))

X_training: (1536, 2000) Y_training: (2, 2000)
Xv: (1536, 1000) Yv: (2, 1000)
Etiquetas únicas: [0 1] [0 1]


## 2. Cálculo de $W$ usando distintos métodos

A partir de $X_t$, $Y_t$:
1. Ecuaciones normales (Cholesky)
2. SVD
3. QR (Householder y Gram-Schmidt)

Cada método debe calcular la pseudo-inversa X⁺ correspondiente y luego $W = Y_t X⁺$

In [5]:
XT = Xt.T
Q, R= QR_con_GS(XT, False)

WGS = pinvGramSchmidt(Q, R, Yt)

In [4]:
XT = Xt.T
Q, R= QR_con_HH(XT)

WHH = pinvHouseHolder(Q, R, Yt)

In [3]:
A = Xt @ traspuesta(Xt)
L = calculaCholesky(A)                                 

WEN = pinvEcuacionesNormales(L, Yt, traspuesta(Xt))

In [ ]:
U, s, VT = svd_reducida(Xt)

WSVD = pinvSVD(U, s, VT, Yt, tol=1e-12)

In [6]:
# HH 
YHH = WHH @ Xv

pred = argmax_axis0(YHH)
true = argmax_axis0(Yv)

MHH, acc, p = confusion_matrix(true, pred)
print(MHH)
print("Accuracy:", acc)
print('Precisión:', p)

[[340 160]
 [241 259]]
Accuracy: 0.599
Precisión: [0.58519793 0.61813842]


In [7]:
# GS
YGS = WGS @ Xv

pred = argmax_axis0(YGS)
true = argmax_axis0(Yv)

MGS, acc, p = confusion_matrix(true, pred)
print(MGS)
print("Accuracy:", acc)
print('Precisión:', p)

[[334 166]
 [150 350]]
Accuracy: 0.684
Precisión: [0.69008264 0.67829457]


In [8]:
# SVD
YSVD = WSVD @ Xv

pred = argmax_axis0(YSVD)
true = argmax_axis0(Yv)

MSVD, acc, p = confusion_matrix(true, pred)
print(MSVD)
print("Accuracy:", acc)
print('Precisión:', p)

[[327 173]
 [152 348]]
Accuracy: 0.675
Precisión: [0.68267223 0.66794626]


In [9]:
YEN = WEN @ Xv

pred = argmax_axis0(YEN)
true = argmax_axis0(Yv)

MEN, acc, p = confusion_matrix(true, pred)
print(MEN)
print("Accuracy:", acc)
print('Precisión:', p)

[[433  67]
 [301 199]]
Accuracy: 0.632
Precisión: [0.58991826 0.7481203 ]
